name: Linting

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          check-name: clj-kondo report
          github_token: ${{ secrets.GITHUB_TOKEN }}
