name: Outdated dependencies
on:
  push:
  schedule:
    - cron: '17 0/2 * * *'
jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquidz/antq-action@main
