name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Prepare java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          tools-deps: 1.11.1.1252

      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Execute clojure code
        run: clojure -M:test:runner
