name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        distribution: ['zulu', 'temurin']
        java: ['8', '11', '16', '17']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          tools-deps: 1.11.4.1474

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Execute clojure code
        run: clojure -M:test:runner
